idf_component_register(
    SRCS
        "test_main.c"
        "../common/test_fault_manager.c"
        "../../framework/core/test/test_nfw_lifecycle.c"
        "../../framework/platform/test/test_nfw_memory.c"
        "../../framework/platform/test/test_nfw_mutex.c"
    INCLUDE_DIRS
        "../common"
    REQUIRES
        unity
        common
        core
        platform
)