idf_component_register(
    SRCS
        "test_main.c"
        "../common/test_fault_manager.c"
"../common/test_condition_monitor.c"
        "../../framework/core/test/test_nfw_lifecycle.c"
        "../../framework/platform/test/test_nfw_memory.c"
        "../../framework/platform/test/test_nfw_mutex.c"
      "../../framework/nfw_hal/test/test_nfw_gpio.c"
"../../framework/nfw_hal/test/test_nfw_uart.c"
"../../framework/nfw_hal/test/test_nfw_delay.c"
    INCLUDE_DIRS
        "../common"
    REQUIRES
        unity
        common
        core
        platform
        nfw_hal
)